services:
  nvim-devcontainer:
    image: nvim-dev:latest
    hostname: nvim-dev
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USER_GID=$USER_GID
        - USER_UID=$USER_UID
    volumes:
      - ./nvim-config:/workspace
      - ./nvim-config:/home/rafalj/.config/nvim
    working_dir: /workspace
    environment:
      - TERM=xterm-256color
