services:
  base-image:
    image: base-image:latest
    build:
      context: ./project

  nvim-devcontainer:
    image: nvim-dev:latest
    hostname: nvim-dev
    build:
      context: .
      args:
        - USER_GID=$USER_GID
        - USER_UID=$USER_UID
        - BASE_IMAGE=base-image:latest
    volumes:
      - ./project:/workspace
    working_dir: /workspace
    environment:
      - TERM=xterm-256color
