services:
  devcontainer:
    image: &_image nvim-dev:latest
    hostname: nvim-dev
    build:
      context: .
      args:
        - USER_GID=$USER_GID
        - USER_UID=$USER_UID
    volumes: &_volumes
      - ./project:/workspace
      - ~/.ssh:/home/rafalj/.ssh
    working_dir: &_working_dir
      /workspace
    devices: &_devices
      - "/dev/bus/usb:/dev/bus/usb"
    environment: &_environment
      - TERM=xterm-256color

  bash:
    image: *_image
    volumes: *_volumes
    working_dir: *_working_dir
    devices: *_devices
    environment: *_environment
    depends_on:
      - devcontainer
    command: "bash"
    stdin_open: true
    tty: true

  develop:
    image: *_image
    volumes: *_volumes
    working_dir: *_working_dir
    devices: *_devices
    environment: *_environment
    depends_on:
      - devcontainer
    command: "nvim ."
    stdin_open: true
    tty: true
