services:
  base-image:
    image: base-image:latest
    build:
      context: ./project

  devcontainer:
    image: nvim-dev:latest
    hostname: nvim-dev
    build:
      context: .
      args:
        - USER_GID=$USER_GID
        - USER_UID=$USER_UID
        - BASE_IMAGE=base-image:latest
    volumes:
      - ./project:/workspace
      - ~/.ssh:/home/rafalj/.ssh
    working_dir: /workspace
    devices:
      - "/dev/bus/usb:/dev/bus/usb"
    environment:
      - TERM=xterm-256color
  bash:
    image: nvim-dev:latest
    working_dir: /workspace
    volumes:
      - ./project:/workspace
    command: "nvim ."
    stdin_open: true
    tty: true
  nvim:
    image: nvim-dev:latest
    working_dir: /workspace
    volumes:
      - ./project:/workspace
    command: "nvim ."
    stdin_open: true
    tty: true
