services:
  devcontainer:
    image: &_image devcontainer:latest
    hostname: &_hostname devcontainer
    build:
      context: .
      args:
        - USER_GID=$USER_GID
        - USER_UID=$USER_UID
    volumes: &_volumes
      - ~/.ssh:/home/rafalj/.ssh
    working_dir: &_working_dir /home/rafalj
    environment: &_environment
      - TERM=xterm-256color

  bash:
    image: *_image
    hostname: *_hostname
    volumes: *_volumes
    working_dir: *_working_dir
    environment: *_environment
    depends_on:
      - devcontainer
    command: "bash"
    stdin_open: true
    tty: true

  nvim:
    image: *_image
    hostname: *_hostname
    volumes: *_volumes
    working_dir: *_working_dir
    environment: *_environment
    depends_on:
      - devcontainer
    command: "nvim ."
    stdin_open: true
    tty: true

  config:
    image: *_image
    hostname: *_hostname
    volumes:
      - ./nvim-config:/config
      - ./nvim-config:/home/rafalj/.config/nvim
      - ~/.ssh/:/home/rafalj/.ssh
    working_dir: /config
    environment: *_environment
    depends_on:
      - devcontainer

